name: aggregation

services:
  db:
    container_name: postgres_container
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-aggregation}
    user: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB:-aggregation} -U ${POSTGRES_USER:-user} -h localhost -p 5432" ]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    volumes:
      - local_data:/var/lib/postgresql/data

volumes:
  local_data:
  pgadmin_data:

