"""first

Revision ID: b9d20e914454
Revises:
Create Date: 2025-03-31 02:26:01.187174

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b9d20e914454"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dividends",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("registry_closing_date", sa.Date(), nullable=False),
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("value", sa.Numeric(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "processed_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("expenses", sa.Numeric(), nullable=False),
        sa.Column("shares", sa.Integer(), nullable=False),
        sa.Column("capitalization", sa.Numeric(), nullable=False),
        sa.Column("price", sa.Numeric(), nullable=False),
        sa.Column("monthly_balance", sa.Numeric(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "results_trades",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("closing_price", sa.Numeric(), nullable=True),
        sa.Column("last_page", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("results_trades")
    op.drop_table("processed_data")
    op.drop_table("dividends")
    # ### end Alembic commands ###
