"""Removing the third table

Revision ID: c558b5a4d156
Revises: b9d20e914454
Create Date: 2025-04-21 01:22:50.825684

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c558b5a4d156"
down_revision: Union[str, None] = "b9d20e914454"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("processed_data")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "processed_data",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("ticker", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "expenses", sa.NUMERIC(), autoincrement=False, nullable=False
        ),
        sa.Column("shares", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "capitalization", sa.NUMERIC(), autoincrement=False, nullable=False
        ),
        sa.Column("price", sa.NUMERIC(), autoincrement=False, nullable=False),
        sa.Column(
            "monthly_balance",
            sa.NUMERIC(),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="processed_data_pkey"),
    )
    # ### end Alembic commands ###
